/*
 * Frame.java
 *
 * Created on __DATE__, __TIME__
 */

package pro1;

/**
 *
 * @author  __USER__
 */
public class Frame extends javax.swing.JFrame {

	/** Creates new form Frame */
	public Frame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jColorChooser1 = new javax.swing.JColorChooser();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();
		jMenuBar3 = new javax.swing.JMenuBar();
		jMenu5 = new javax.swing.JMenu();
		jMenu6 = new javax.swing.JMenu();
		µÇÂ¼ = new java.awt.Button();
		µÇÂ¼1 = new java.awt.Button();
		jToolBar1 = new javax.swing.JToolBar();
		jDesktopPane1 = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		jLabel1.setText("\u6b22\u8fce\u8fdb\u5165\u56fe\u5f62\u7528\u6237\u754c\u9762");

		jLabel2.setText("jLabel2");

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(
				jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jFrame1Layout.createSequentialGroup()
								.addGap(83, 83, 83).addComponent(jLabel1)
								.addContainerGap(458, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jFrame1Layout.createSequentialGroup()
								.addContainerGap(549, Short.MAX_VALUE)
								.addComponent(jLabel2).addGap(90, 90, 90)));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jFrame1Layout.createSequentialGroup().addGap(46, 46, 46)
						.addComponent(jLabel1).addGap(142, 142, 142)
						.addComponent(jLabel2)
						.addContainerGap(285, Short.MAX_VALUE)));

		jMenu3.setText("File");
		jMenuBar2.add(jMenu3);

		jMenu4.setText("Edit");
		jMenuBar2.add(jMenu4);

		jMenu5.setText("File");
		jMenuBar3.add(jMenu5);

		jMenu6.setText("Edit");
		jMenuBar3.add(jMenu6);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		µÇÂ¼.setLabel("button1");
		µÇÂ¼.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				µÇÂ¼ActionPerformed(evt);
			}
		});

		µÇÂ¼1.setLabel("button1");
		µÇÂ¼1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				µÇÂ¼1ActionPerformed(evt);
			}
		});

		jToolBar1.setRollover(true);

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(264, 264, 264)
								.addComponent(µÇÂ¼,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(39, 39, 39)
								.addComponent(µÇÂ¼1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										150, Short.MAX_VALUE)
								.addComponent(jDesktopPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										259,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(55, 55, 55))
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										75,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(806, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										267, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														µÇÂ¼,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														µÇÂ¼1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(212, 212, 212))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(52, 52, 52)
								.addComponent(jDesktopPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										341,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(137, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void µÇÂ¼1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void µÇÂ¼ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JColorChooser jColorChooser1;
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuBar jMenuBar3;
	private javax.swing.JToolBar jToolBar1;
	private java.awt.Button µÇÂ¼;
	private java.awt.Button µÇÂ¼1;
	// End of variables declaration//GEN-END:variables

}